import { Product, Category, LookbookItem } from "@/app/types";

export const products: Product[] = [
  {
    id: "1",
    name: "Eternal Solitaire",
    category: "rings",
    price: 12500,
    materials: ["gold", "platinum", "rose-gold"],
    description: "A timeless diamond solitaire set in pure elegance. The Eternal Solitaire features a brilliant-cut diamond that captures light from every angle.",
    image: "/images/ring-solitaire.jpg",
    featured: true,
  },
  {
    id: "2",
    name: "Celestial Halo",
    category: "rings",
    price: 18900,
    materials: ["gold", "platinum"],
    description: "Surrounded by a halo of smaller diamonds, this ring creates an ethereal glow that mesmerizes from every angle.",
    image: "/images/ring-halo.jpg",
    featured: true,
  },
  {
    id: "3",
    name: "Midnight Pendant",
    category: "necklaces",
    price: 8400,
    materials: ["gold", "silver", "rose-gold"],
    description: "A deep sapphire embraced by diamond accents, suspended on a delicate chain that catches the light with every movement.",
    image: "/images/necklace-pendant.jpg",
    featured: true,
  },
  {
    id: "4",
    name: "Aurora Drops",
    category: "earrings",
    price: 6200,
    materials: ["gold", "platinum", "rose-gold"],
    description: "Cascading diamonds that dance with light, inspired by the ethereal beauty of the northern lights.",
    image: "/images/earrings-aurora.jpg",
    featured: true,
  },
  {
    id: "5",
    name: "Infinity Band",
    category: "rings",
    price: 4500,
    materials: ["gold", "silver", "rose-gold", "platinum"],
    description: "An endless circle of diamonds symbolizing eternal love and commitment.",
    image: "/images/ring-infinity.jpg",
  },
  {
    id: "6",
    name: "Royal Choker",
    category: "necklaces",
    price: 28000,
    materials: ["gold", "platinum"],
    description: "A statement piece worthy of royalty, featuring emerald-cut diamonds in an intricate lattice design.",
    image: "/images/necklace-choker.jpg",
    featured: true,
  },
  {
    id: "7",
    name: "Stellar Studs",
    category: "earrings",
    price: 3200,
    materials: ["gold", "silver", "rose-gold"],
    description: "Classic diamond studs that bring starlight to your everyday elegance.",
    image: "/images/earrings-studs.jpg",
  },
  {
    id: "8",
    name: "Serpent Cuff",
    category: "bracelets",
    price: 15600,
    materials: ["gold", "silver"],
    description: "A mesmerizing serpent design encrusted with pavé diamonds, wrapping elegantly around the wrist.",
    image: "/images/bracelet-serpent.jpg",
    featured: true,
  },
];

export const categories: Category[] = [
  {
    id: "rings",
    name: "Rings",
    description: "Symbols of eternal commitment and personal expression",
    image: "/images/category-rings.jpg",
    count: 24,
  },
  {
    id: "necklaces",
    name: "Necklaces",
    description: "Elegant statements that frame your beauty",
    image: "/images/category-necklaces.jpg",
    count: 18,
  },
  {
    id: "earrings",
    name: "Earrings",
    description: "Sparkling accents for every occasion",
    image: "/images/category-earrings.jpg",
    count: 32,
  },
  {
    id: "bracelets",
    name: "Bracelets",
    description: "Delicate chains to bold cuffs",
    image: "/images/category-bracelets.jpg",
    count: 15,
  },
];

export const lookbookItems: LookbookItem[] = [
  {
    id: "1",
    title: "Midnight Gala",
    image: "/images/lookbook-1.jpg",
    products: ["3", "4", "6"],
  },
  {
    id: "2",
    title: "Golden Hour",
    image: "/images/lookbook-2.jpg",
    products: ["1", "8"],
  },
  {
    id: "3",
    title: "Eternal Promise",
    image: "/images/lookbook-3.jpg",
    products: ["1", "5"],
  },
  {
    id: "4",
    title: "Celestial Dreams",
    image: "/images/lookbook-4.jpg",
    products: ["2", "4", "7"],
  },
];
